export const genres = [
    {
      name: "Random",
      description: "Get a surprise genre selected just for you",
      image: "random.webp",
      characters: [
        { name: "Captain Fantastic", image: "placeholder.png", description: "A fantastic superhero" },
        { name: "Mighty Mouse", image: "placeholder.png", description: "A mighty mouse" },
        { name: "Super Ted", image: "placeholder.png", description: "A super teddy bear" },
        { name: "Bananaman", image: "placeholder.png", description: "A banana superhero" },
        { name: "Danger Mouse", image: "placeholder.png", description: "A secret agent mouse" },
        { name: "Mr. Incredible", image: "placeholder.png", description: "A super strong hero" },
        { name: "Elastigirl", image: "placeholder.png", description: "A stretchy superhero" },
        { name: "Dash Parr", image: "placeholder.png", description: "A super fast boy" },
        { name: "Violet Parr", image: "placeholder.png", description: "A girl with invisibility powers" },
        { name: "Jack-Jack Parr", image: "placeholder.png", description: "A baby with multiple powers" },
        { name: "Frozone", image: "placeholder.png", description: "A superhero with ice powers" },
        { name: "Buzz Lightyear", image: "placeholder.png", description: "A space ranger" },
        { name: "Woody", image: "placeholder.png", description: "A cowboy toy" },
        { name: "Jessie", image: "placeholder.png", description: "A cowgirl toy" },
        { name: "Duke Caboom", image: "placeholder.png", description: "A stuntman toy" },
        { name: "Bo Peep", image: "placeholder.png", description: "A shepherdess toy" },
        { name: "Slinky Dog", image: "placeholder.png", description: "A slinky dog toy" },
        { name: "Rex", image: "placeholder.png", description: "A dinosaur toy" },
        { name: "Hamm", image: "placeholder.png", description: "A piggy bank toy" },
        { name: "Bullseye", image: "placeholder.png", description: "A toy horse" }
      ]
    },
    {
      name: "Adventure",
      description: "Journeys that excite and test the limits of the imagination.",
      image: "adventure1.webp",
      characters: [
        { name: "Ava Stormchaser", image: "adventure/avaStormchaser.webp", description: "A fearless adventurer with a knack for finding ancient artifacts." },
        { name: "Leo Wildheart", image: "adventure/Leo_Wildheart.webp", description: "A brave explorer known for his daring jungle expeditions." },
        { name: "Sierra Quickstep", image: "adventure/Sierra_Quickstep.webp", description: "An agile climber who excels in mountain adventures." },
        { name: "Max Thunderfoot", image: "adventure/Max_Thunderfoot.webp", description: "A strong and resilient tracker with a passion for the wild." },
        { name: "Zara Windrider", image: "adventure/Zara_Windrider.webp", description: "An expert sailor and navigator of treacherous seas." },
        { name: "Finn Skywalker", image: "adventure/Finn_Skywalker.webp", description: "A pilot who loves exploring uncharted skies." },
        { name: "Nina Earthshaker", image: "adventure/Nina_Earthshaker.webp", description: "A geologist who seeks the mysteries hidden beneath the earth." },
        { name: "Jake Riverclimber", image: "adventure/Jake_Riverclimber.webp", description: "A skilled rafter who navigates the toughest rapids." },
        { name: "Ella Nightshade", image: "adventure/Ella_Nightshade.webp", description: "A stealthy and resourceful treasure hunter." },
        { name: "Kai Firebrand", image: "adventure/Kai_Firebrand.webp", description: "An energetic and bold desert explorer." },
        { name: "Finn Wilder", image: "adventure/.webp", description: "An astronomer and space adventurer." },
        { name: "Bella Swift", image: "adventure/.webp", description: "A robust adventurer who conquers rocky terrains." },
        { name: "Zane Thunder", image: "adventure/.webp", description: "A botanist who thrives in dense, unexplored forests." },
        { name: "Kira Quest", image: "adventure/.webp", description: "An adventurer who loves the challenge of arctic expeditions." },
        { name: "Liam Falcon", image: "adventure/.webp", description: "A deep-sea diver with a passion for underwater caves." },
        { name: "Nina Brave", image: "adventure/.webp", description: "An archaeologist who uncovers ancient ruins in deserts." },
        { name: "Rex Raptor", image: "adventure/.webp", description: "A daring storm chaser who captures the beauty of nature’s fury." },
        { name: "Mia Venture", image: "adventure/.webp", description: "A night explorer who finds hidden treasures under the moonlight." },
        { name: "Kai Strider", image: "adventure/.webp", description: "An explorer who braves thunderous mountains and valleys." },
        { name: "Elsa Ocean", image: "adventure/.webp", description: "A delicate but determined adventurer who follows the whispers of the wind to new discoveries." }
      ]
    },
    {
      name: "Fantasy",
      description: "Where magic rules and adventure beckons.",
      image: "fantasy1.webp",
      characters: [
        { name: "Arwen Starseeker", image: "placeholder.png", description: "A graceful elf" },
        { name: "Thorn Oakenshield", image: "placeholder.png", description: "A rugged dwarf" },
        { name: "Lyra Moonshadow", image: "placeholder.png", description: "A mysterious elf" },
        { name: "Eldrin the Wise", image: "placeholder.png", description: "An elderly wizard" },
        { name: "Seraphina Fireheart", image: "placeholder.png", description: "A fierce warrior" },
        { name: "Griffin Stormrider", image: "placeholder.png", description: "A valiant knight" },
        { name: "Aurora Dreamweaver", image: "placeholder.png", description: "A serene elf" },
        { name: "Finnan Lightfoot", image: "placeholder.png", description: "A nimble halfling" },
        { name: "Elara Swiftwind", image: "placeholder.png", description: "A swift ranger" },
        { name: "Kael Frostblade", image: "placeholder.png", description: "A formidable warrior" },
        { name: "Luna Silvermoon", image: "placeholder.png", description: "A mystical elf" },
        { name: "Gareth Dragonbane", image: "placeholder.png", description: "A brave knight" },
        { name: "Mira Starlight", image: "placeholder.png", description: "A gentle elf" },
        { name: "Alaric the Brave", image: "placeholder.png", description: "A heroic knight" },
        { name: "Elysia Nightshade", image: "placeholder.png", description: "A dark elf" },
        { name: "Ronan Earthshaker", image: "placeholder.png", description: "A mighty dwarf" },
        { name: "Isla Moonwhisper", image: "placeholder.png", description: "A mystical elf" },
        { name: "Orin Shadowhunter", image: "placeholder.png", description: "A stealthy rogue" },
        { name: "Celeste Starfall", image: "placeholder.png", description: "A celestial being" },
        { name: "Zephyr Windrider", image: "placeholder.png", description: "A swift elf" }
      ]
    },
    {
      name: "Mystery",
      description: "Unravel secrets in a world where every clue counts.",
      image: "mystery.webp",
      characters: [
        { name: "Sherlock Holmes", image: "placeholder.png", description: "A famous detective" },
        { name: "Nancy Drew", image: "placeholder.png", description: "A teenage detective" },
        { name: "Hercule Poirot", image: "placeholder.png", description: "A Belgian detective" },
        { name: "Miss Marple", image: "placeholder.png", description: "An elderly detective" },
        { name: "Jessica Fletcher", image: "placeholder.png", description: "A mystery writer and detective" },
        { name: "Sam Spade", image: "placeholder.png", description: "A private detective" },
        { name: "Philip Marlowe", image: "placeholder.png", description: "A private eye" },
        { name: "Veronica Mars", image: "placeholder.png", description: "A teenage sleuth" },
        { name: "Harry Bosch", image: "placeholder.png", description: "A LAPD detective" },
        { name: "Chet Gecko", image: "placeholder.png", description: "A gecko detective" },
        { name: "Trixie Belden", image: "placeholder.png", description: "A teenage detective" },
        { name: "Enola Holmes", image: "placeholder.png", description: "Sherlock Holmes' sister" },
        { name: "Agatha Raisin", image: "placeholder.png", description: "A public relations agent turned detective" },
        { name: "Inspector Gadget", image: "placeholder.png", description: "A bumbling detective with gadgets" },
        { name: "Ace Ventura", image: "placeholder.png", description: "A pet detective" },
        { name: "Adrian Monk", image: "placeholder.png", description: "A detective with OCD" },
        { name: "Detective Pikachu", image: "placeholder.png", description: "A detective Pokemon" },
        { name: "Kinsey Millhone", image: "placeholder.png", description: "A private investigator" },
        { name: "Eliot Ness", image: "placeholder.png", description: "A Prohibition agent" },
        { name: "Temperance Brennan", image: "placeholder.png", description: "A forensic anthropologist" }
      ]
    },
    {
      name: "Science Fiction",
      description: "Explorations of the future and beyond through science's lens.",
      image: "scifi.webp",
      characters: [
        { name: "Luke Skywalker", image: "placeholder.png", description: "A Jedi Knight" },
        { name: "Leia Organa", image: "placeholder.png", description: "A princess and leader" },
        { name: "Han Solo", image: "placeholder.png", description: "A smuggler turned hero" },
        { name: "Ellen Ripley", image: "placeholder.png", description: "A space warrior" },
        { name: "Sarah Connor", image: "placeholder.png", description: "A mother of a future savior" },
        { name: "John Carter", image: "placeholder.png", description: "A Civil War soldier on Mars" },
        { name: "Tron", image: "placeholder.png", description: "A computer program warrior" },
        { name: "Neo", image: "placeholder.png", description: "The One" },
        { name: "Morpheus", image: "placeholder.png", description: "A mentor to Neo" },
        { name: "Spock", image: "placeholder.png", description: "A Vulcan science officer" },
        { name: "James T. Kirk", image: "placeholder.png", description: "A starship captain" },
        { name: "Jean-Luc Picard", image: "placeholder.png", description: "A starship captain" },
        { name: "Data", image: "placeholder.png", description: "An android officer" },
        { name: "Seven of Nine", image: "placeholder.png", description: "A former Borg drone" },
        { name: "The Doctor", image: "placeholder.png", description: "A time-traveling alien" },
        { name: "River Song", image: "placeholder.png", description: "A time traveler" },
        { name: "Marty McFly", image: "placeholder.png", description: "A time-traveling teenager" },
        { name: "Doc Brown", image: "placeholder.png", description: "A time-traveling scientist" },
        { name: "Roy Batty", image: "placeholder.png", description: "A replicant" },
        { name: "Deckard", image: "placeholder.png", description: "A blade runner" }
      ]
    },
    {
      name: "Short Story",
      description: "Bite-sized tales packed with a punch.",
      image: "short.webp",
      characters: [
        { name: "Tom Sawyer", image: "placeholder.png", description: "A mischievous boy" },
        { name: "Huckleberry Finn", image: "placeholder.png", description: "A adventurous boy" },
        { name: "Pip", image: "placeholder.png", description: "An orphan boy" },
        { name: "Ebenezer Scrooge", image: "placeholder.png", description: "A miserly old man" },
        { name: "Oliver Twist", image: "placeholder.png", description: "An orphan boy" },
        { name: "Heidi", image: "placeholder.png", description: "A girl from the Alps" },
        { name: "Alice", image: "placeholder.png", description: "A girl in Wonderland" },
        { name: "Dorothy Gale", image: "placeholder.png", description: "A girl in Oz" },
        { name: "Peter Pan", image: "placeholder.png", description: "A boy who never grows up" },
        { name: "Wendy Darling", image: "placeholder.png", description: "A girl in Neverland" },
        { name: "Frodo Baggins", image: "placeholder.png", description: "A hobbit on a quest" },
        { name: "Samwise Gamgee", image: "placeholder.png", description: "A loyal hobbit" },
        { name: "Bilbo Baggins", image: "placeholder.png", description: "A hobbit on an adventure" },
        { name: "Gandalf", image: "placeholder.png", description: "A wise wizard" },
        { name: "Aragorn", image: "placeholder.png", description: "A ranger and king" },
        { name: "Legolas", image: "placeholder.png", description: "An elf archer" },
        { name: "Gimli", image: "placeholder.png", description: "A dwarf warrior" },
        { name: "Smeagol", image: "placeholder.png", description: "A creature corrupted by the ring" },
        { name: "Sherlock Holmes", image: "placeholder.png", description: "A famous detective" },
        { name: "Dr. Watson", image: "placeholder.png", description: "A detective's assistant" }
      ]
    }
  ];